// export const baseUrl = 'https://api.churchee.app/api/v1';
export const webiste = 'https://api.churchee.app';
export const chatURL = 'http://ec2-3-81-141-121.compute-1.amazonaws.com:8080';
export const chatService = `${chatURL}/api/v1`;
const baseUrl = 'http://localhost:9090/api/v1';


export const api = {
  createAccount: baseUrl + '/user/member',
  verify: baseUrl + '/auth/verify/member',
  login: baseUrl + '/auth/both',
  getMe: baseUrl + '/user/me',
  live: baseUrl + '/live/member',
  logout: baseUrl + '/auth/mobile/logout',
  changePassword: baseUrl + '/change-password',
  profile: baseUrl + '/profile',
  image: baseUrl + '/image',
  header: baseUrl + '/header/member',
  localImg: baseUrl + '/user/img/',
  img: 'https://dlvr7v2twt32x.cloudfront.net/',
  backups: baseUrl + '/backups',
  createAcctMethod: baseUrl + '/user/member/source',
  emailExist: baseUrl + '/email',
  sermon: baseUrl + '/sermon/member',
  createAnonymousPR: baseUrl + '/pr/anonymous',
  createPR: baseUrl + '/pr',
  prayerView: baseUrl + '/pr/pray',
  personalPrayer: baseUrl + '/pr/personal',
  getPersonalPR: baseUrl + '/pr/personal',
  getPR: baseUrl + '/pr/member',
  getPRWall: baseUrl + '/pr/wall',
  getEvent: baseUrl + '/event/member',
  getDevotion: baseUrl + '/devotion/member',
  getHymn: baseUrl + '/hymn/member',
  note: baseUrl + '/note',
  bible: baseUrl + '/bible',
  bibleBook: baseUrl + '/bible/book',
  bibleChapter: baseUrl + '/bible/chapter',
  biblePassage: baseUrl + '/bible/passage',
  savedEvents: baseUrl + '/event/member/saved',
  media: baseUrl + '/media/member',
  form: baseUrl + '/form',
  newMember: baseUrl + '/newMember',
  volunteer: baseUrl + '/volunteer',
  childDedicaton: baseUrl + '/child/dedication',
  reset: baseUrl + '/mail/forgot',
  give: baseUrl + '/give/history',
  savedItem: baseUrl + '/user/save/item',
  favouriteMedia: baseUrl + '/favourite/media',
  dailyVerse: baseUrl + '/dailyverse/member',
  country: baseUrl + '/country',
  church: baseUrl + '/user/find-church',
  getAllMembers: baseUrl + '/user/all/members',
  searchChurch: `${baseUrl}/user/search-church`,
  recommendation: `${baseUrl}/user/recommendation`,
  topChurch: `${baseUrl}/user/top/church`,
  join: `${baseUrl}/user/join`,

  // room service
  createRoom: `${chatService}/room/create`,
  getRoom: `${chatService}/room/get`,
  joinRoom: `${chatService}/member/add`,
  poolMessage: `${chatURL}/poolMessage`,
  getMembers: `${chatService}/room/getMembers`,
  messageStatus: `${chatURL}/messageStatus`,
};