const img = {
  register: require('../assets/images/Register.png'),
  registerIconDark: require('../assets/images/RegisterIconDark.png'),
  registerIconLight: require('../assets/images/RegisterIconLight.png'),
  login: require('../assets/images/login.png'),
  loginIconDark: require('../assets/images/loginIconDark.png'),
  loginIconLight: require('../assets/images/loginIconLight.png'),
  eventSection: require('../assets/images/home/events.png'),
  sermonSection: require('../assets/images/home/sermon.jpg'),
  devotionSection: require('../assets/images/home/devotion.png'),
  mediaSection: require('../assets/images/home/media.png'),
  prayerSection: require('../assets/images/home/prayer.png'),
  giveSection: require('../assets/images/home/give.jpg'),
  formSection: require('../assets/images/home/form.jpg'),
  hymnSection: require('../assets/images/home/hymn.jpg'),
  chatSection: require('../assets/images/home/chat.png'),
  bgImg: require('../assets/images/icons/logo.png'),
  tithe: require('../assets/images/tithe.jpeg'),
  findChurch: require('../assets/images/findChurch.png'),
  offering: require('../assets/images/offering.jpeg'),
  vows: require('../assets/images/vows.jpeg'),
  firstfruit: require('../assets/images/firstfruit.jpeg'),
  building: require('../assets/images/building.jpeg'),
  history: require('../assets/images/history.png'),
  welcome: require('../assets/images/welcome.jpg'),
  childDedication: require('../assets/images/childDedication.jpeg'),
  connection: require('../assets/images/form/connection.jpg'),
  volunteer: require('../assets/images/form/volunteer.jpg'),
  membership: require('../assets/images/form/membership.jpeg'),
  feedback: require('../assets/images/form/feedback.jpg'),
  survey: require('../assets/images/form/survey.jpg'),
  usflag: require('../assets/images/usflag.png'),
  user: require('../assets/images/icons/user.png'),
};

export default img;