const img = Object.freeze({
  register: require('../assets/images/Register.png'),
  registerIconDark: require('../assets/images/RegisterIconDark.png'),
  registerIconLight: require('../assets/images/RegisterIconLight.png'),
  login: require('../assets/images/login.png'),
  loginIconDark: require('../assets/images/loginIconDark.png'),
  loginIconLight: require('../assets/images/loginIconLight.png'),

  // home
  'event-light': require('../assets/images/home/event-light.jpg'),
  'event-dark': require('../assets/images/home/event-dark.jpg'),
  'sermon-light': require('../assets/images/home/sermon-light.jpg'),
  'sermon-dark': require('../assets/images/home/sermon-dark.jpg'),
  'devotion-light': require('../assets/images/home/devotion-light.jpg'),
  'devotion-dark': require('../assets/images/home/devotion-dark.jpg'),
  'media-light': require('../assets/images/home/media-light.jpg'),
  'media-dark': require('../assets/images/home/media-dark.jpg'),
  'prayer-light': require('../assets/images/home/prayer-light.jpg'),
  'prayer-dark': require('../assets/images/home/prayer-dark.jpg'),
  'give-dark': require('../assets/images/home/give-dark.jpg'),
  'give-light': require('../assets/images/home/give-light.jpg'),
  "form-light": require('../assets/images/home/form-light.jpg'),
  "form-dark": require('../assets/images/home/form-dark.jpg'),
  "hymn-light": require('../assets/images/home/hymn-light.jpg'),
  "hymn-dark": require('../assets/images/home/hymn-dark.jpg'),
  'dailyVerse-dark': require('../assets/images/home/dailyVerse-dark.jpg'),
  'dailyVerse-light': require('../assets/images/home/dailyVerse-light.jpg'),
  'live-light': require('../assets/images/home/live-light.jpg'),
  'live-dark': require('../assets/images/home/live-dark.jpg'),

  bgImg: require('../assets/images/icons/logo.png'),
  tithe: require('../assets/images/tithe.jpeg'),
  findChurch: require('../assets/images/findChurch.png'),
  offering: require('../assets/images/offering.jpeg'),
  vows: require('../assets/images/vows.jpeg'),
  firstfruit: require('../assets/images/firstfruit.jpeg'),
  building: require('../assets/images/building.jpeg'),
  history: require('../assets/images/history.png'),
  welcome: require('../assets/images/welcome.jpg'),
  childDedication: require('../assets/images/childDedication.jpeg'),
  connection: require('../assets/images/form/connection.jpg'),
  volunteer: require('../assets/images/form/volunteer.jpg'),
  membership: require('../assets/images/form/membership.jpeg'),
  feedback: require('../assets/images/form/feedback.jpg'),
  survey: require('../assets/images/form/survey.jpg'),
  usflag: require('../assets/images/usflag.png'),
  user: require('../assets/images/icons/user.png'),
  GoogleIconDark: require('../assets/images/GoogleIconDark.png'),
  GoogleIconLight: require('../assets/images/GoogleIconLight.png'),
  facebook: require('../assets/images/icons/facebook.png'),
  instagram: require('../assets/images/icons/instagram.png'),
  youtube: require('../assets/images/icons/youtube.png'),
  churchFind: require('../assets/images/churchFind.png'),
});

export default img;