export const CHANGE_MODE = 'CHANGE_MODE';
export const CHANGE_FONT_SIZE = 'CHANGE_FONT_SIZE';
export const CHANGE_BASE_COLOR = 'CHANGE_BASE_COLOR';
export const TOGGLE_HOME_SECTIONS = 'TOGGLE_HOME_SECTIONS';
export const HOMEPAGE = 'HOMEPAGE';
export const SET_HEADERS = "SET_HEADERS";

// account
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const UPDATE_AUTH_TOKEN = 'UPDATE_AUTH_TOKEN';
export const UPDATE_AUTH_REFRESH_TOKEN = 'UPDATE_AUTH_REFRESH_TOKEN';
export const UPDATE_CHURCH_DATA = 'UPDATE_CHURCH_DATA';


export const MEDIA_DATA = 'MEDIA_DATA';
export const MEDIA_CURRENT_PAGE = 'MEDIA_CURRENT_PAGE'; 

export const DEVOTION_DATA = 'DEVOTION_DATA';



// bible
export const BIBLE_BOOKS = 'BIBLE_BOOKS';
export const SELECTED_BOOK = 'SELECTED_BOOK';
export const SELECTED_CHAPTER = 'SELECTED_CHAPTER';
export const SELECTED_VERSE = 'SELECTED_VERSE';



// sermon
export const SERMON_DATA = 'SERMON_DATA'; 
export const SERMON_CURRENT_PAGE = 'SERMON_CURRENT_PAGE'; 


// feedback
export const LAUNCH_FEEDBACK = 'LAUNCH_FEEDBACK';
export const DISMISS_FEEDBACK = 'DISMISS_FEEDBACK';


// country
export const COUNTRY_DATA = 'COUNTRY_DATA';
export const STATE_DATA = 'STATE_DATA';